crisi:
  username: Crisidev
  password: Crisipassword
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university_dev
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update